name: perf benchmarking
description: Runs perf benchmarking across provided commands
author: James <james@eli.cx>
inputs:
  config:
    description: Benchmark config
    required: false
    default: .perf.json
runs:
  using: node20
  main: dist/index.js
